# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/absl-py-0.8.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/astor-0.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/c-ares-1.15.0-h01d97ff_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2019.6.16-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/certifi-2019.6.16-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/flask-1.1.1-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/freetype-2.10.0-h24853df_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gast-0.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/grpcio-1.22.0-py36h6ef0057_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/h5py-2.9.0-nompi_py36h6248fd5_1104.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/hdf5-1.10.5-nompi_h0cbb7df_1103.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/itsdangerous-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jinja2-2.10.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jpeg-9c-h1de35cc_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/keras-applications-1.0.8-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/keras-preprocessing-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.8.0-12_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.8.0-12_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-8.0.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxxabi-8.0.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.2.1-h6de7cb9_1006.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-3.0.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.8.0-12_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libopenblas-0.3.7-hd44dcd8_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libpng-1.6.37-h2573ce8_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libprotobuf-3.9.1-hfbae3c0_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libtiff-4.0.10-hd08fb8f_1003.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lz4-c-1.8.3-h6de7cb9_1001.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/markdown-3.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/markupsafe-1.1.1-py36h1de35cc_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/ncurses-6.1-h0a44026_1002.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/numpy-1.17.1-py36h6b0580a_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/openssl-1.1.1c-h01d97ff_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pip-19.2.3-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/protobuf-3.9.1-py36h6de7cb9_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python-3.6.7-h94afb7f_1005.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/readline-8.0-hcfe32e1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scipy-1.3.1-py36hab3da7d_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/setuptools-41.2.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/six-1.12.0-py36_1000.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/sqlite-3.29.0-hb7d70f7_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tensorboard-1.13.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tensorflow-1.13.1-py36_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tensorflow-estimator-1.13.0-py36h24bf2e0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/termcolor-1.1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.9-h2573ce8_1002.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/werkzeug-0.15.5-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/wheel-0.33.6-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/xz-5.2.4-h1de35cc_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zlib-1.2.11-h01d97ff_1005.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/zstd-1.4.0-ha9f0a20_0.tar.bz2
